{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "multicalculatorcanary.fullname" . }}
  labels:
    {{- include "multicalculatorcanary.labels" . | nindent 4 }}
  {{- if .Values.ingress.canary }}
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-header: "canary"
    nginx.ingress.kubernetes.io/canary-weight: "{{ .Values.ingress.weight }}"
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- else }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.ingress.host | quote }}
      secretName: {{ include "multicalculatorcanary.fullname" . }}-tls
{{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path:
            backend:
              serviceName: {{ include "multicalculatorcanary.fullname" . }}-frontend-svc
              servicePort: {{ .Values.service.port }}
{{- end }}
